name: DevSecOps Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        pip install -r app/requirements.txt

    - name: Validate Python Code
      run: |
        python -m py_compile app/app.py

    - name: Install Trivy Scanner
      run: |
        sudo apt-get update
        sudo apt-get install wget -y
        wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.1_Linux-64bit.deb
        sudo dpkg -i trivy_0.50.1_Linux-64bit.deb

    - name: Scan Filesystem Vulnerabilities
      run: |
        trivy fs . --exit-code 0 --severity HIGH,CRITICAL

    - name: Build Docker Image
      run: |
        docker build -t devsecops-app -f docker/Dockerfile .

    - name: Scan Docker Image
      run: |
        trivy image devsecops-app --exit-code 0 --severity HIGH,CRITICAL
